version: "3.8"

volumes:
  mysqldata:


services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    networks: [ devnet ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
